//! Markdown method/trait checklists for shadow mirror reports.

use std::fmt::Write as _;

use crate::error::CordialResult;
use crate::shadow::{ShadowReport, TraitImplCoverage, TypeMethodCoverage};

use tracing::instrument;
/// Render a per-pair method checklist (elicit_doc `shadow-{upstream}.checklist.md` parity).
#[instrument(level = "debug", skip(report), err(level = "warn"))]
pub fn render_shadow_method_checklist(report: &ShadowReport) -> CordialResult<String> {
    let total_methods: usize = report
        .method_coverage
        .iter()
        .map(TypeMethodCoverage::upstream_method_count)
        .chain(
            report
                .missing_type_methods
                .iter()
                .map(|entry| entry.missing.len()),
        )
        .sum();
    let covered_methods: usize = report
        .method_coverage
        .iter()
        .map(|entry| entry.covered.len())
        .sum();
    let pct = if total_methods == 0 {
        0.0
    } else {
        covered_methods as f64 / total_methods as f64 * 100.0
    };

    let mut out = String::new();
    writeln!(
        out,
        "# `{}` → `{}` method checklist",
        report.target_crate, report.shadow_crate
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "_Generated by cordial · {covered_methods}/{total_methods} methods covered ({pct:.1}%) · \
         {type_count} mirrored types with method maps_",
        type_count = report.method_coverage.len() + report.missing_type_methods.len()
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "The shadow crate is a drop-in replacement: every upstream method name should appear \
         on the matching shadow type."
    )?;
    writeln!(out)?;

    if !report.trait_coverage.is_empty() {
        writeln!(out, "## Trait impl gaps")?;
        writeln!(out)?;
        for entry in &report.trait_coverage {
            write_trait_section(&mut out, entry)?;
        }
    }

    let mut with_gaps: Vec<_> = report
        .method_coverage
        .iter()
        .filter(|entry| !entry.missing.is_empty())
        .collect();
    with_gaps.sort_by_key(|entry| entry.upstream_type.as_str());

    let mut complete: Vec<_> = report
        .method_coverage
        .iter()
        .filter(|entry| entry.missing.is_empty() && !entry.covered.is_empty())
        .collect();
    complete.sort_by_key(|entry| entry.upstream_type.as_str());

    if !with_gaps.is_empty() {
        writeln!(out, "## Methods to add")?;
        writeln!(out)?;
        for entry in with_gaps {
            write_type_method_section(&mut out, entry)?;
        }
    }

    if !report.missing_type_methods.is_empty() {
        writeln!(out, "## Methods on unshadowed types")?;
        writeln!(out)?;
        for entry in &report.missing_type_methods {
            writeln!(
                out,
                "### `{}` ({} methods)",
                entry.upstream_type,
                entry.missing.len()
            )?;
            writeln!(out)?;
            for name in &entry.missing {
                writeln!(out, "- [ ] `{name}`")?;
            }
            writeln!(out)?;
        }
    }

    if !complete.is_empty() {
        writeln!(out, "## Complete types")?;
        writeln!(out)?;
        for entry in complete {
            let count = entry.covered.len();
            writeln!(
                out,
                "- [x] `{}` ↔ `{}` ({count}/{count} methods)",
                entry.upstream_type, entry.shadow_type
            )?;
        }
        writeln!(out)?;
    }

    Ok(out)
}

#[instrument(level = "info", skip(entry), err(level = "warn"))]
fn write_type_method_section(out: &mut String, entry: &TypeMethodCoverage) -> CordialResult<()> {
    let total = entry.upstream_method_count();
    writeln!(
        out,
        "### `{}` ↔ `{}` ({} / {total})",
        entry.upstream_type,
        entry.shadow_type,
        entry.covered.len()
    )?;
    writeln!(out)?;
    for name in &entry.missing {
        writeln!(out, "- [ ] `{name}`")?;
    }
    for name in &entry.covered {
        writeln!(out, "- [x] `{name}`")?;
    }
    if !entry.extra.is_empty() {
        writeln!(out)?;
        writeln!(out, "_Extra methods in shadow (not in upstream):_")?;
        for name in &entry.extra {
            writeln!(out, "- `{name}`")?;
        }
    }
    writeln!(out)?;
    Ok(())
}

#[instrument(level = "info", skip(entry), err(level = "warn"))]
fn write_trait_section(out: &mut String, entry: &TraitImplCoverage) -> CordialResult<()> {
    writeln!(out, "### `{}`", entry.trait_path)?;
    writeln!(out)?;
    if !entry.missing_on_shadow.is_empty() {
        writeln!(out, "_Missing on shadow types:_")?;
        for name in &entry.missing_on_shadow {
            writeln!(out, "- [ ] `{name}`")?;
        }
    }
    if !entry.covered_on_shadow.is_empty() {
        writeln!(out, "_Present on shadow types:_")?;
        for name in &entry.covered_on_shadow {
            writeln!(out, "- [x] `{name}`")?;
        }
    }
    writeln!(out)?;
    Ok(())
}
